name: Nowhere
version: 1.2
main: me.lepsima.nowhere.Main
api-version: 1.21
description: Nowhere

permissions:
  nowhere.bypass:
    description: Allows place and destroy access to the nowhere dimension
    default: op

commands:
  guidebook:
    description: Gives the player the server's guide book
    usage: /guidebook

  chatcolor:
    description: Changes your color in the chat
    usage: /chatcolor

  bankadmin:
    description: Create and remove banks
    usage: /bankadmin
    permission: op

  bankmanage:
    description: Manage your bank
    usage: /bankmanage

  banktrade:
    description: Trade
    usage: /banktrade

  joinevent:
    description: Participate in the event
    usage: /joinevent

  leaveevent:
    description: Leave the event
    usage: /leaveevent

  introevent:
    usage: /introevent

  setintroevent:
    usage: /setintroevent
    permission: op

  getenterkey:
    usage: /getenterkey
    permission: op

  getexitkey:
    usage: /getexitkey
    permission: op

  tpnowhere:
    usage: /tpnowhere
    permission: op

  tpworld:
    usage: /tpworld
    permission: op